version: '1.0'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: profiler-db
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: